import { v4 as uuidv4 } from 'uuid';

export const projectData = [
  {
    id: uuidv4(),
    name: 'Tetris',
    cover: '/tetris.png',
    description:
      'In the dark , We come out and play We are its children, And were here to stay Running through , Hungry for strays No invitation, take me away Im not cruel, But thats still what you see Club to club, Come see this city with me',
  },
  {
    id: uuidv4(),
    name: 'Sunnyside',
    cover: '/muimbaji-hero-image.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolor laborum dicta voluptates officia aspernatur modi nisi, consequatur voluptatum alias adipisci aliquam temporibus minima id quasi mollitia deserunt enim? Labore facilis cupiditate quos vero sunt tempore!',
  },
  {
    id: uuidv4(),
    name: 'Sunnyvale',
    cover: '/sunnyside.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolor laborum dicta voluptates officia aspernatur modi nisi, consequatur voluptatum alias adipisci aliquam temporibus minima id quasi mollitia deserunt enim? Labore facilis cupiditate quos vero sunt tempore!',
  },
  {
    id: uuidv4(),
    name: 'Tetromino',
    cover: '/tetris.png',
    description:
      'In the dark , We come out and play We are its children, And were here to stay Running through , Hungry for strays No invitation, take me away Im not cruel, But thats still what you see Club to club, Come see this city with me',
  },
];

// export const projectDetails = [
//   {
//     id: projectData[0].id,
//     name: 'Muimbaji',
//     mainImage: '',
//     description:
//       "I'm baby unicorn mukbang flannel palo santo poke vexillologist activated charcoal praxis vaporware authentic. Normcore solarpunk yuccie leggings ascot poke literally mixtape blog. Tumeric vice 90's tilde cred. Same meh actually, dreamcatcher narwhal asymmetrical distillery before they sold out bruh farm-to-table tacos cronut whatever. Microdosing grailed vice offal aesthetic everyday carry. Selvage tilde schlitz keytar hell of deep v. Church-key pok pok JOMO photo booth bitters, gluten-free twee lumbersexual hella.",
//     musicPageImage: '',
//     musicPageDesc:
//       "Hashtag locavore sus crucifix, copper mug mukbang tilde freegan kombucha woke portland humblebrag sustainable. Man bun street art squid, brunch JOMO portland chillwave 90's swag marxism mumblecore cray. Yr marfa solarpunk tacos gluten-free. Portland freegan meditation, locavore microdosing lomo everyday carry. Af kogi venmo air plant.",
//     videoPageImage: '',
//     videoDescImage: '',
//     videoPageDesc:
//       'Cupping marxism brunch try-hard, beard fashion axe blackbird spyplane bushwick adaptogen yes plz 3 wolf moon man bun biodiesel venmo. Succulents praxis forage, hashtag chia tousled hammock VHS distillery bespoke taxidermy. Keffiyeh jawn cardigan bitters heirloom glossier tousled direct trade knausgaard tote bag gentrify yuccie etsy. Forage tote bag green juice air plant, big mood leggings cardigan narwhal affogato.',
//     galleryPageImage: '',
//     galleryImage: '',
//     galleryPageDesc:
//       'Meditation synth humblebrag typewriter kale chips salvia, austin XOXO shaman. Ramps fit put a bird on it pug blue bottle. Hot chicken hella 3 wolf moon mustache mlkshk sartorial biodiesel ethical cray. Gatekeep sustainable pop-up, austin selvage photo booth raw denim semiotics tacos tumeric. Occupy PBR&B drinking vinegar try-hard aesthetic chartreuse biodiesel normcore mlkshk.',
//   },
//   {
//     id: projectData[1].id,
//     name: 'Capture',
//     mainImage: '',
//     description:
//       "Get out of town, I didn't know you did anything creative. Ah, let me read some. Anyway, Grandpa hit him with the car and brought him into the house. He seemed so helpless, like a little lost puppy, my heart just went out for him. That's Calvin Klein, oh my god, he's a dream. McFly. Yeah, you got my homework finished, McFly?",
//     musicPageImage: '',
//     musicPageDesc:
//       "Alright, McFly, you're asking for it, and now you're gonna get it. I think it's terrible. Girls chasing boys. When I was your age I never chased a boy, or called a boy, or sat in a parked car with a boy. Damn, where is that kid. Damn. Damn damn. You're late, do you have no concept of time? Indeed I will, roll em. I, Doctor Emmett Brown, am about to embark on an historic journey. What have I been thinking of, I almost forgot to bring some extra plutonium. How did I ever expect to get back, one pallet one trip I must be out of my mind. What is it Einy? Oh my god, they found me, I don't know how but they found me. Run for it, Marty. Well, Biff.",
//     videoPageImage: '',
//     videoDescImage: '',
//     videoPageDesc:
//       "Right. I've gotta go. I'll be at my grandma's. Here, let me give you the number. Bye. Well uh, good, fine. See, there's Biff out there waxing it right now. Now, Biff, I wanna make sure that we get two coats of wax this time, not just one.",
//     galleryPageImage: '',
//     galleryImage: '',
//     galleryPageDesc:
//       'Breakfast. What, well you mean like a date? On the night I go back in time, you get- Doc. Weight has nothing to do with it. Re-elect Mayor Goldie Wilson. Progress is his middle name.',
//   },
//   {
//     id: projectData[2].id,
//     name: 'Similar Studios Africa',
//     mainImage: '',
//     description:
//       "Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.",
//     musicPageImage: '',
//     musicPageDesc:
//       "Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.",
//     videoPageImage: '',
//     videoDescImage: '',
//     videoPageDesc:
//       "Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?",
//     galleryPageImage: '',
//     galleryImage: '',
//     galleryPageDesc:
//       "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?",
//   },
//   {
//     id: projectData[3].id,
//     name: 'Prosound Ke',
//     mainImage: '',
//     description:
//       'Bro ipsum dolor sit amet bonk taco wack berm face shots fatty chillax heli avie. Face plant park rat dust on crust, stomp dope sketching bowl. Whip laps hardtail stoked berm corn shuttle euro newschooler dust on crust rock-ectomy bowl. Bail park park rat, carbon smear grind air bunny slope wheelie gaper roadie free ride washboard snake bite. Dirtbag couloir BB gondy 360.',
//     musicPageImage: '',
//     musicPageDesc:
//       'Bowl carve ACL, huck bomb shuttle pow pow dust on crust flowy lid Whistler steeps travel pinner. Air rail couloir washboard hurl carcass McTwist line shred dope huckfest frozen chicken heads. Bonk hurl carcass heli, bear trap fully rail north shore nose wheelie drop drop bunny slope. Bear trap grip tape rock roll DH bowl poaching gondy berm avie. Rail dope flowy, gnar grom titanium white room huck crank rail single track. Trucks dope moguls bunny slope dirt, pow hero steed chain suck bear trap Ski flow.',
//     videoPageImage: '',
//     videoDescImage: '',
//     videoPageDesc:
//       'Schwag dope giblets epic couloir moguls. North shore endo washboard wheelie BB stoked, gondy bomb hole glades cork chillax. Air nose ripping snake bite 360 betty. Titanium huck beater schwag OTB caballerial sucker hole pow pow air whip dust on crust first tracks ride wheels. Smear bro bomb hole, twin tip hammer huck gapers ripping rail bonk betty chowder. Switch trucks pow bowl cornice ripper first tracks skid bail yard sale.',
//     galleryPageImage: '',
//     galleryImage: '',
//     galleryPageDesc:
//       'Core shot switch sucker hole twin tip, steed table top huck Whistler huck lid T-bar ride snake bite spread eagle. Frozen chicken heads ACL newschooler phat, 180 twin tip bomb air cork pillow popping bear trap spread eagle tele. Whistler air frozen chicken heads free ride greasy backside, chowder caballerial DH dope. Single track phat ripping steed bump. Huckfest dust on crust afterbang, travel ripper bear trap heli.',
//   },
// ];

export const projectQuery = [
  {
    project: 'muimbaji',
    data: {
      buildId: uuidv4(),
      isFallback: false,
      is_interactive: false,
      theme: 'custom',
      custom_theme: {
        background: {
          alpha: 1,
          _type: 'color',
          hex: '#1d568f',
          name: 'bg-red-500',
          hsv: {
            a: 1,
            s: 0.018181818181818243,
            v: 0.43137254901960786,
            _type: 'hsvaColor',
            h: 210.00000000000023,
          },
          rgb: {
            g: 109,
            _type: 'rgbaColor',
            a: 1,
            b: 110,
            r: 108,
          },
          hsl: {
            a: 1,
            s: 0.009174311926605536,
            _type: 'hslaColor',
            h: 210.00000000000023,
            l: 0.4274509803921569,
          },
        },
        text: {
          rgb: {
            a: 1,
            b: 255,
            r: 255,
            g: 255,
            _type: 'rgbaColor',
          },
          hsl: {
            a: 1,
            s: 0,
            _type: 'hslaColor',
            h: 200,
            l: 1,
          },
          alpha: 1,
          _type: 'color',
          hex: '#ffffff',
          hsv: {
            a: 1,
            s: 0,
            v: 1,
            _type: 'hsvaColor',
            h: 200,
          },
        },
      },
      meta_description:
        'A project aimed at making an artist showcase website, making it a onestop shop for anything related to the artist',
      meta_image: '/muimbaji-hero-image.png',
      name: 'Muimbaji',
      intro:
        "A self-initiated project aimed at making an artist showcase website. The website contains all information pertaining to the artist with builtin players for both audio and video files, and an eshop for selling merchandise. It's aimed at making sure everything about the artist can be found under one roof.",
      meta_title: 'Muimbaji',
      tags: [
        { name: 'Design' },
        { name: 'UI' },
        { name: 'UX' },
        { name: 'Next.js' },
      ],
      content: [
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: 'Logo',
          copy: 'The logo for Muimbaji comes from the working name. I was going to use Fishbowl as the project name before switching to Muimbaji.',
          _type: 'project_image',
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
            image: '/muimbaji-logo.png',
          },
          image_alt: null,
          include_caption: true,
          caption: 'Logo for the Muimbaji project.',
          image_is_decorative: true,
          image_size: 'medium',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 200,
            aspectRatio: 1.6,
            height: 200,
          },
          include_cta: 'none',
          link_file: null,
          link_internal_type: null,
          cta_text: null,
          link_internal: null,
          link_external: null,
        },
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: 'Intro',
          copy: null,
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-home-mobile.png',
          },
          image: '/muimbaji-home-mobile.png',
          image_alt: 'Screenshot of Muimbaji intro page with the menu open.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 812,
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-home-mobile.png',
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: null,
          copy: "The intro page contains sections containing the artist's about information, their latest music video, upcoming events and latest releases.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-home-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji intro page - about section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-home-mobile-3.png',
              image_alt:
                'Screenshot of Muimbaji intro page - upcoming events section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Music',
          copy: "The music page contains the artist's dicography with a tracks and albums section.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-music-mobile.png',
              image_alt: 'Screenshot of Muimbaji music page - tracks section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-music-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji music page - albums section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'right',
          copy_heading: 'Music player',
          copy: 'The tracks on the music page are playable using the custom music player located at the bottom of the page.',
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-music-mobile-4.png',
          },
          image: '/muimbaji-music-mobile-4.png',
          image_alt: 'Screenshot of Muimbaji audio player interface.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 70,
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: null,
          copy: 'The music player also expands to reveal details about other platforms where the track is available and details about the track.',
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-music-mobile-4.png',
          },
          image: '/muimbaji-music-mobile-3.png',
          image_alt: 'Screenshot of Muimbaji track details.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 812,
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Media',
          copy: 'The media page contains a music videos section and a gallery showcasing images related to the artist,',
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-media-mobile.png',
              image_alt: 'Screenshot of Muimbaji media page - videos section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji media page - gallery section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-3.png',
              image_alt:
                'Screenshot of Muimbaji video section - expanded to details view.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-4.png',
              image_alt:
                'Screenshot of Muimbaji gallery section - expanded to single media view.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Shop',
          copy: "The shop page connects to an ecommerce site for selling the artist's merchandise. Payment processing is connected through stripe. The shop itself is built using Next.js, Strapi, and is connected to a PostgreSQL for storing data and Auth0 for authenticating and managing user data.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-shop-mobile.png',
              image_alt: 'Screenshot of Muimbaji shop page',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji shop page - item details view',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-3.png',
              image_alt: 'Screenshot of Muimbaji shop page - cart section',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-4.png',
              image_alt: 'Screenshot of Muimbaji shop page - checkout section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          copy: 'Github',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://github.com/kei-en/muimbaji',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
          },
          image: null,
          copy_heading: 'View Project',
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
        {
          copy: 'Production',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://muimbaji.vercel.app',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
          },
          image: null,
          copy_heading: null,
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
      ],
    },
  },
  {
    project: 'mtindo',
    data: {
      buildId: uuidv4(),
      isFallback: false,
      is_interactive: false,
      theme: 'custom',
      custom_theme: {
        background: {
          alpha: 1,
          _type: 'color',
          hex: '#6c6d6e',
          hsv: {
            a: 1,
            s: 0.018181818181818243,
            v: 0.43137254901960786,
            _type: 'hsvaColor',
            h: 210.00000000000023,
          },
          rgb: {
            g: 109,
            _type: 'rgbaColor',
            a: 1,
            b: 110,
            r: 108,
          },
          hsl: {
            a: 1,
            s: 0.009174311926605536,
            _type: 'hslaColor',
            h: 210.00000000000023,
            l: 0.4274509803921569,
          },
        },
        text: {
          rgb: {
            a: 1,
            b: 255,
            r: 255,
            g: 255,
            _type: 'rgbaColor',
          },
          hsl: {
            a: 1,
            s: 0,
            _type: 'hslaColor',
            h: 200,
            l: 1,
          },
          alpha: 1,
          _type: 'color',
          hex: '#ffffff',
          hsv: {
            a: 1,
            s: 0,
            v: 1,
            _type: 'hsvaColor',
            h: 200,
          },
        },
      },
      meta_description:
        'A project aimed at making an artist showcase website, making it a onestop shop for anything related to the artist',
      meta_image: '/tetris.png',
      name: 'Mtindo',
      intro:
        "A self-initiated project aimed at making an artist showcase website. The website contains all information pertaining to the artist with builtin players for both audio and video files, and an eshop for selling merchandise. It's aimed at making sure everything about the artist can be found under one roof.",
      meta_title: 'Mtindo',
      tags: [
        { name: 'Design' },
        { name: 'UI' },
        { name: 'UX' },
        { name: 'Next.js' },
      ],
      content: [
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: 'Logo',
          copy: 'The logo for Muimbaji comes from the working name. I was going to use Fishbowl as the project name before switching to Muimbaji.',
          _type: 'project_image',
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
            image: '/muimbaji-logo.png',
          },
          image_alt: null,
          include_caption: true,
          caption: 'Logo for the Muimbaji project.',
          image_is_decorative: true,
          image_size: 'medium',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 200,
            aspectRatio: 1.6,
            height: 200,
          },
          include_cta: 'none',
          link_file: null,
          link_internal_type: null,
          cta_text: null,
          link_internal: null,
          link_external: null,
        },
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: 'Intro',
          copy: null,
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-home-mobile.png',
          },
          image: '/muimbaji-home-mobile.png',
          image_alt: 'Screenshot of Muimbaji intro page with the menu open.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 812,
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-home-mobile.png',
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'below',
          copy_heading: null,
          copy: "The intro page contains sections containing the artist's about information, their latest music video, upcoming events and latest releases.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-home-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji intro page - about section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-home-mobile-3.png',
              image_alt:
                'Screenshot of Muimbaji intro page - upcoming events section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Music',
          copy: "The music page contains the artist's dicography with a tracks and albums section.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-music-mobile.png',
              image_alt: 'Screenshot of Muimbaji music page - tracks section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-music-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji music page - albums section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'right',
          copy_heading: 'Music player',
          copy: 'The tracks on the music page are playable using the custom music player located at the bottom of the page.',
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-music-mobile-4.png',
          },
          image: '/muimbaji-music-mobile-4.png',
          image_alt: 'Screenshot of Muimbaji audio player interface.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 70,
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: null,
          copy: 'The music player also expands to reveal details about other platforms where the track is available and details about the track.',
          _type: 'project_image',
          devices: {
            image_desktop: '/muimbaji-home-desktop.png',
            image_tablet: '/muimbaji-home-tablet.png',
            image_mobile: '/muimbaji-music-mobile-4.png',
          },
          image: '/muimbaji-music-mobile-3.png',
          image_alt: 'Screenshot of Muimbaji track details.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          image_dimensions: {
            _type: 'mobile.imageDimensions',
            width: 375,
            aspectRatio: 3.3333333333333335,
            height: 812,
          },
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Media',
          copy: 'The media page contains a music videos section and a gallery showcasing images related to the artist,',
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-media-mobile.png',
              image_alt: 'Screenshot of Muimbaji media page - videos section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji media page - gallery section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-3.png',
              image_alt:
                'Screenshot of Muimbaji video section - expanded to details view.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-media-mobile-4.png',
              image_alt:
                'Screenshot of Muimbaji gallery section - expanded to single media view.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Shop',
          copy: "The shop page connects to an ecommerce site for selling the artist's merchandise. Payment processing is connected through stripe. The shop itself is built using Next.js, Strapi, and is connected to a PostgreSQL for storing data and Auth0 for authenticating and managing user data.",
          _type: 'project_image_grid',
          columns: 2,
          image_size: 'medium',
          items: [
            {
              image: '/muimbaji-shop-mobile.png',
              image_alt: 'Screenshot of Muimbaji shop page',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-2.png',
              image_alt: 'Screenshot of Muimbaji shop page - item details view',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-3.png',
              image_alt: 'Screenshot of Muimbaji shop page - cart section',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
            {
              image: '/muimbaji-shop-mobile-4.png',
              image_alt: 'Screenshot of Muimbaji shop page - checkout section.',
              include_caption: false,
              caption: null,
              image_is_decorative: false,
              image_dimensions: {
                _type: 'mobile.imageDimensions',
                width: 375,
                aspectRatio: 3.3333333333333335,
                height: 812,
              },
            },
          ],
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          copy: 'Github',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://github.com/kei-en/muimbaji',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
          },
          image: null,
          copy_heading: 'View Project',
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
        {
          copy: 'Production',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://muimbaji.vercel.app',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            image_desktop: null,
            image_tablet: null,
            image_mobile: null,
          },
          image: null,
          copy_heading: null,
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
      ],
    },
  },
];
